add_newline = false
command_timeout = 1000

format = "$os$directory$git_branch$git_status$git_state$git_metrics$c$cpp$golang$java$nodejs$deno$bun$php$python$ruby$rust$lua$dart$zig$elixir$haskell$kotlin$scala$swift$terraform$nix_shell$conda$docker_context$kubernetes$aws$gcloud$azure$status$cmd_duration$jobs$sudo$character"

[os]
disabled = false
format = "[$symbol]($style)"
style = "bold #50C878"

[os.symbols]
Arch = " "
Alpine = " "
Debian = " "
Fedora = " "
Linux = " "
Macos = " "
Ubuntu = " "
Windows = " "

[directory]
format = " [ $path]($style)[$read_only]($read_only_style) "
style = "bold #50C878"
read_only = " 🔒"
read_only_style = "bold red"
truncation_length = 3
truncation_symbol = " …/"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "bold purple"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "bold red"
conflicted = "󰞇 "
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕ ⇡${ahead_count} ⇣${behind_count}"
untracked = "󰡯 "
stashed = " "
modified = "󰏫 "
staged = "󰪥 "
renamed = "󰑕 "
deleted = "󰆴 "

[git_state]
format = '[\($state( $progress_current/$progress_total)\)]($style) '
style = "bold yellow"

[git_metrics]
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
added_style = "bold green"
deleted_style = "bold red"
disabled = false

[golang]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold #00ADD8"

[nodejs]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold #8CC84B"

[deno]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold white"

[bun]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold #FBF0DF"

[python]
format = "[$symbol$version( \\($virtualenv\\))]($style) "
symbol = " "
style = "bold #3776AB"

[java]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold red"

[c]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold blue"

[cpp]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold purple"

[rust]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold #CE412B"

[php]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold #4F5D95"

[ruby]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold red"

[lua]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold #000080"

[dart]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold #0175C2"

[zig]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold #F7A41D"

[elixir]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold #4E2A8E"

[haskell]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold #5D4F85"

[kotlin]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold #7F52FF"

[scala]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold #DC322F"

[swift]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold #F05138"

[terraform]
format = "[$symbol($version )]($style)"
symbol = "󱁢 "
style = "bold #844FBA"

[nix_shell]
format = "[$symbol($state )]($style)"
symbol = " "
style = "bold #7E7EFF"

[conda]
format = "[$symbol($environment )]($style)"
symbol = " "
style = "bold #44A833"

[docker_context]
format = "[$symbol$context]($style) "
symbol = " "
style = "bold blue"

[kubernetes]
format = "[$symbol$context( \\($namespace\\))]($style) "
symbol = "󱃾 "
style = "bold #326CE5"
disabled = false

[aws]
format = "[$symbol($profile )(\\($region\\) )]($style)"
symbol = " "
style = "bold #FF9900"

[gcloud]
format = "[$symbol$account(@$domain)(\\($region\\))]($style) "
symbol = "󱇶 "
style = "bold #4285F4"

[azure]
format = "[$symbol($subscription)]($style) "
symbol = "󰠅 "
style = "bold #008AD7"

[status]
disabled = false
symbol = "❌ "
format = "[$symbol$status]($style) "
style = "bold red"

[sudo]
disabled = false
symbol = "🧙 "
format = "[$symbol]($style)"

[jobs]
symbol = "✦ "
format = "[$symbol$number]($style) "
style = "bold cyan"

[cmd_duration]
format = "[ $duration]($style)"
style = "bold yellow"

[character]
success_symbol = "[❯](bold #50C878) "
error_symbol = "[X](bold #DC322F) "
