# Extra autostart processes
# exec-once = uwsm-app -- my-service
#exec-once = swww-daemon
# exec-once = omarchy-theme-bg-next
exec-once = ags run ~/.config/ags
exec-once = sleep 4 && ags toggle "todo-cards"
