# Variables
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

# Applications
bindd = SUPER, RETURN, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
bindr = SUPER, B, exec, ags toggle work-pill
bindr = SUPER, SUPER_L, exec, ags toggle hud
# 0
bindd = SUPER, KP_Insert, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
# 1
bindd = SUPER, KP_End, Terminal, exec, helium-browser
# 2
bindd = SUPER, KP_Down, File manager, exec, uwsm-app -- nautilus --new-window
# 3
bindd = SUPER, KP_Next, Terminal, exec, dbeaver
# 4
bindd = SUPER, KP_Left, Insomnia, exec, insomnia

# TUI tools
bindd = CTRL SHIFT, I, Activity, exec, ~/.config/hypr/scripts/term-run.sh "btop"
bind  = CTRL SHIFT, S,           exec, ~/.config/hypr/scripts/term-run.sh "lazyssh"
bind  = CTRL SHIFT, Q,           exec, ~/.config/hypr/scripts/term-run.sh "sqlit"
bind  = CTRL SHIFT, G,           exec, ~/.config/hypr/scripts/term-run.sh "lazygit"
bind  = CTRL SHIFT, R,           exec, ~/.config/hypr/scripts/term-run.sh "lazyshark"
bind  = CTRL SHIFT, C,           exec, ~/.config/hypr/scripts/term-run.sh "lazydocker"
bind  = CTRL SHIFT, U,           exec, ~/.config/hypr/scripts/term-run.sh "lazydisk"
bind  = CTRL SHIFT, M,           exec, ~/.config/hypr/scripts/term-run.sh "lazysystem"
bind  = CTRL SHIFT, B,           exec, ~/.config/hypr/scripts/term-run.sh "sudo lazyband"
bind  = CTRL SHIFT, P,           exec, ~/.config/hypr/scripts/term-run.sh "tmux a || tmux"
bind  = CTRL SHIFT, O,           exec, ~/.config/hypr/scripts/term-run.sh "opencode"
bind  = CTRL SHIFT, N,           exec, ~/.config/hypr/scripts/term-run.sh "nvim"


# Clipboard
unbind = SUPER, C
bindd = SUPER, C, Clipboard manager, exec, omarchy-launch-walker -m clipboard
# Zoxide
bind = SUPER, Z, exec, sh -c 'query=$(echo | walker --dmenu); [ -n "$query" ] && target=$(zoxide query "$query") && alacritty --working-directory "$target" -e bash -c "exec bash"'
# Track
unbind = SUPER, T
bindd = SUPER, T, Track/Untrack estudo, exec, ~/.config/hypr/scripts/track-untrack.sh

# Tarefas - 9
bindd = SUPER, KP_Prior, Tarefas, exec, ~/.config/hypr/scripts/toggle-vittae.sh tarefas.md
# Cronograma - 8
bindd = SUPER, KP_Up, Cronograma, exec, ~/.config/hypr/scripts/toggle-vittae.sh cronograma.csv
# Habitos - 7
bindd = SUPER, KP_Home, Hábitos, exec, ~/.config/hypr/scripts/toggle-vittae.sh habitos.csv
# Estudos - 6
bindd = SUPER, KP_Right, Hábitos, exec, ~/.config/hypr/scripts/toggle-vittae.sh estudos.csv

bindd = SUPER, L, Bloco de notas, exec, alacritty -e nvim ~/tmp/notas.md

# UI
unbind = SUPER SHIFT, mouse_up
unbind = SUPER SHIFT, mouse_down
bindd = SUPER SHIFT, mouse_down, Zoom In, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/^float/ {print $2 + 2.0}')
bindd = SUPER SHIFT, mouse_up, Zoom Out, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/^float/ {v=$2-2.0; print (v<1?1:v)}')
