monitor=HDMI-A-2,1440x900@59,0x0,1
monitor=eDP-1,1920x1080@165,1440x0,1

bind = SUPER, 1, focusworkspaceoncurrentmonitor, 1
bind = SUPER, 2, focusworkspaceoncurrentmonitor, 2
bind = SUPER, 3, focusworkspaceoncurrentmonitor, 3
